"""
api/routes/terraform.py
========================
Two endpoints — completely isolated from the existing Pulumi deploy flow.

POST /api/terraform/preview
    Body: { nodes, edges, namespace, project, region }
    Returns a summary of what *would* be generated (no file creation).

POST /api/terraform/generate
    Body: { nodes, edges, namespace, project, region }
    Returns a zip archive with all .tf files as a binary download.

The route is registered in main.py with:
    app.include_router(terraform.router)

No changes required to any existing file.
"""
from __future__ import annotations

import io
import logging
import zipfile
from typing import Optional

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
import os

# ── Import the TF engine (pure module, no Pulumi dependency) ─────────────────
from terraform_gen import generate_terraform, generate_terraform_summary

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/terraform", tags=["terraform"])


# ── Request model — mirrors DeployPayload but is independent ─────────────────

class TerraformPayload(BaseModel):
    nodes:     list[dict]
    edges:     list[dict]
    namespace: str = Field(default="default")
    project:   str = Field(
        default_factory=lambda: os.getenv("DEFAULT_GCP_PROJECT", "my-gcp-project")
    )
    region: str = Field(
        default_factory=lambda: os.getenv("DEFAULT_GCP_REGION", "us-central1")
    )


# ── Preview ───────────────────────────────────────────────────────────────────

@router.post("/preview")
async def terraform_preview(payload: TerraformPayload):
    """
    Return a JSON summary of what Terraform files would contain.
    No files are created; useful for showing a "what will be generated" panel.
    """
    ns = payload.namespace
    logger.info(
        "TF preview: namespace=%s nodes=%d project=%s region=%s",
        ns, len(payload.nodes), payload.project, payload.region,
    )
    summary = generate_terraform_summary(
        nodes=payload.nodes,
        edges=payload.edges,
    )
    return {
        "namespace": ns,
        "project":   payload.project,
        "region":    payload.region,
        **summary,
    }


# ── Generate + Download ───────────────────────────────────────────────────────

@router.post("/generate")
async def terraform_generate(payload: TerraformPayload):
    """
    Generate a complete Terraform workspace and return it as a zip download.

    The zip contains:
      vco-terraform/
        versions.tf
        variables.tf
        terraform.tfvars
        main.tf
        outputs.tf
        README.md

    The caller (browser) receives it as  vco-terraform.zip.
    """
    ns = payload.namespace
    logger.info(
        "TF generate: namespace=%s nodes=%d project=%s region=%s",
        ns, len(payload.nodes), payload.project, payload.region,
    )

    # ── Generate HCL files ────────────────────────────────────────────────────
    files: dict[str, str] = generate_terraform(
        nodes=payload.nodes,
        edges=payload.edges,
        project=payload.project,
        region=payload.region,
    )

    # ── Add README ────────────────────────────────────────────────────────────
    node_count = sum(
        1 for n in payload.nodes
        if n.get("type") not in ("vpcGroup", "groupBox", "")
    )
    files["README.md"] = _readme(
        project=payload.project,
        region=payload.region,
        namespace=ns,
        node_count=node_count,
    )

    # ── Zip all files ─────────────────────────────────────────────────────────
    zip_buffer = io.BytesIO()
    folder = "vco-terraform"

    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        for filename, content in files.items():
            zf.writestr(f"{folder}/{filename}", content.encode("utf-8"))

    zip_buffer.seek(0)

    logger.info("TF zip created: %d files  %d bytes", len(files), zip_buffer.getbuffer().nbytes)

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={
            "Content-Disposition": 'attachment; filename="vco-terraform.zip"',
            "X-VCO-Namespace":     ns,
            "X-VCO-Node-Count":    str(node_count),
        },
    )


# ── README template ───────────────────────────────────────────────────────────

def _readme(project: str, region: str, namespace: str, node_count: int) -> str:
    return f"""\
# VCO — Generated Terraform Workspace

Generated by **Visual Cloud Orchestrator** from namespace `{namespace}`.

| Field     | Value           |
|-----------|-----------------|
| Project   | `{project}`     |
| Region    | `{region}`      |
| Resources | {node_count}    |

## Quick Start

```bash
# 1. Install Terraform ≥ 1.5
# 2. Authenticate with GCP
gcloud auth application-default login

# 3. Edit terraform.tfvars — set project_id and region
nano terraform.tfvars

# 4. Initialise and deploy
terraform init
terraform plan
terraform apply
```

## File Layout

| File                | Purpose                                          |
|---------------------|--------------------------------------------------|
| `versions.tf`       | Terraform + provider version constraints         |
| `variables.tf`      | All input variable declarations                  |
| `terraform.tfvars`  | Default values — **edit before running**         |
| `main.tf`           | All GCP resource and data-source blocks          |
| `outputs.tf`        | Exported values (URLs, names, IDs)               |

## State Backend (Recommended)

For team use, add a remote backend to `versions.tf`:

```hcl
terraform {{
  backend "gcs" {{
    bucket = "your-tfstate-bucket"
    prefix = "vco/{namespace}"
  }}
}}
```

## Notes

- Resources tagged with `# Uncomment ...` are optional and commented out.
- Cloud Run services default to `INGRESS_TRAFFIC_INTERNAL_ONLY`.
  Change to `INGRESS_TRAFFIC_ALL` if you need public access.
- Service accounts are created by Terraform. Ensure the executor has
  `roles/iam.serviceAccountAdmin` in the target project.
"""
